// by Adam Porembinski
//
// Problem 2 from ProjectEuler.net
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
//     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values 
// do not exceed four million, find the sum of the even-valued terms.

#include <cstdio>

int main() 
{
    int first = 1;
    int second = 1;

    int below = 4000000;
    int wynik = 0;
    int tmp = 0;  //temporary for storing value


    while(true)
    {
        tmp = first + second;
        if(tmp >= below)
        {
            break;
        }

        //printf("%i \n", tmp);  //DEBUG ONLY!!

        if(tmp % 2 == 0)
        {
            //printf("%i \n", tmp);  //DEBUG ONLY!!
            wynik = wynik + tmp;
        }

        first = second;
        second = tmp;
    }

    printf("Wynik: %i", wynik);
    return 0;
}
